include:
  - local: '.gitlab/ci/prebuild.yml'
  - remote: https://gitlab.com/ynezz/openwrt-ci/raw/master/openwrt-ci/gitlab/main.yml

stages:
  - pre-build
  - deploy

.build site:
  stage: pre-build
  image: debian:9
  before_script:
    - apt-get update; apt-get install -y make python3 ca-certificates git
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - build

build site for target environment using scrape method:
  extends: .build site
  script:
    - cp -R ./www ./build
    - sed -i "s;%GIT_VERSION%;$(git describe --tags);" build/index.html
    - misc/collect.py scrape https://downloads.openwrt.org build

.deploy:
  stage: deploy
  image: alpine
  dependencies:
    - build site for target environment using scrape method
  before_script:
    - apk update && apk add rsync
    - echo $RSYNC_PASSWORD | sha256sum
  only:
    - master
    - tags
    - ynezz/rsync-debug
  script:
    - rsync -rlptvz build/ "rsync://firmware_selector@mirror-02.infra.openwrt.org/$RSYNC_TARGET/www/"

deploy to firmware-selector.staging.openwrt.org:
  extends: .deploy
  variables:
    RSYNC_TARGET: firmware-selector-staging-upload

deploy to firmware-selector.openwrt.org:
  extends: .deploy
  variables:
    RSYNC_TARGET: firmware-selector-upload
  when: manual
  only:
    - tags
